name: CI tests

on:
  pull_request:
  push:
    branches:
    - main
    - 'push-action/**'

env:
  PYTEST_ADDOPTS: "--color=yes"
  LINTING_PY_VERSION: "3.9"  # The version of Python to use for linting (typically the minimum supported)

# Cancel running workflows when additional changes are pushed
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python ${{ env.LINTING_PY_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.LINTING_PY_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install .[dev] --extra-index-url https://pip.ccdc.cam.ac.uk

    - name: Run pre-commit
      run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install latest compatible versions of immediate dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install .[dev] --extra-index-url https://pip.ccdc.cam.ac.uk

    - name: Run tests
      run: pytest -rs -vvv
